dataset:
  name: mrm8488/goemotions
  split_train: train
  split_val: validation
  split_test: test
  max_length: 128

model:
  name: bert-base-uncased
  num_labels: 28   # 27 emotions + neutral
  problem_type: multi_label_classification

training:
  batch_size: 16
  learning_rate: 2e-5
  epochs: 4
  weight_decay: 0.01
  warmup_ratio: 0.1

paths:
  model_dir: ./models/goemotions_bert
  logs_dir: ./logs
  results_dir: ./results
